\set ON_ERROR_STOP on

-- Standalone PostgreSQL substitute for the Supabase-only extension and cron
-- setup in 20260824124000_scheduled_email_worker.sql. This file is used only
-- by scripts/test-db-local-postgres.ps1 and is never deployed.
CREATE SCHEMA IF NOT EXISTS cron;

-- Minimal pg_cron-compatible objects for migration replay. They record the
-- intended schedule but never launch background work.
CREATE TABLE IF NOT EXISTS cron.job (
  jobid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jobname TEXT NOT NULL UNIQUE,
  schedule TEXT NOT NULL,
  command TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE OR REPLACE FUNCTION cron.schedule(
  p_jobname TEXT,
  p_schedule TEXT,
  p_command TEXT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
  v_jobid BIGINT;
BEGIN
  INSERT INTO cron.job (jobname, schedule, command, active)
  VALUES (p_jobname, p_schedule, p_command, TRUE)
  ON CONFLICT (jobname) DO UPDATE
    SET schedule = EXCLUDED.schedule,
        command = EXCLUDED.command,
        active = TRUE
  RETURNING jobid INTO v_jobid;

  RETURN v_jobid;
END;
$$;

CREATE OR REPLACE FUNCTION cron.unschedule(p_jobid BIGINT)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
DECLARE
  v_deleted_rows BIGINT;
BEGIN
  DELETE FROM cron.job WHERE jobid = p_jobid;
  GET DIAGNOSTICS v_deleted_rows = ROW_COUNT;
  RETURN v_deleted_rows > 0;
END;
$$;

DROP TRIGGER IF EXISTS trg_auto_process_email_queue ON public.email_queue;
DROP FUNCTION IF EXISTS public.auto_process_email_queue_fn();
DROP FUNCTION IF EXISTS internal.get_service_role_key();

CREATE TABLE IF NOT EXISTS internal.email_worker_invocations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  request_id BIGINT,
  status TEXT NOT NULL CHECK (status IN ('requested', 'configuration_error', 'invocation_error')),
  error_code TEXT
);

REVOKE ALL ON internal.email_worker_invocations FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT ON internal.email_worker_invocations TO service_role;

CREATE OR REPLACE FUNCTION internal.get_vault_secret(p_name TEXT)
RETURNS TEXT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT decrypted_secret
  FROM vault.decrypted_secrets
  WHERE name = p_name
  ORDER BY created_at DESC
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION internal.invoke_email_worker()
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_url TEXT;
  v_secret TEXT;
  v_request_id BIGINT;
BEGIN
  v_url := internal.get_vault_secret('email_worker_url');
  v_secret := internal.get_vault_secret('email_worker_secret');

  IF NULLIF(btrim(v_url), '') IS NULL OR NULLIF(btrim(v_secret), '') IS NULL THEN
    INSERT INTO internal.email_worker_invocations (status, error_code)
    VALUES ('configuration_error', 'WORKER_SECRET_OR_URL_MISSING');
    RETURN NULL;
  END IF;

  SELECT net.http_post(
    url := v_url,
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'X-Queue-Worker-Secret', v_secret
    ),
    body := '{"source":"pg_cron"}'::jsonb,
    timeout_milliseconds := 10000
  ) INTO v_request_id;

  INSERT INTO internal.email_worker_invocations (request_id, status)
  VALUES (v_request_id, 'requested');
  RETURN v_request_id;
EXCEPTION WHEN OTHERS THEN
  INSERT INTO internal.email_worker_invocations (status, error_code)
  VALUES ('invocation_error', SQLSTATE);
  RETURN NULL;
END;
$$;

REVOKE ALL ON FUNCTION internal.get_vault_secret(TEXT) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION internal.invoke_email_worker() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION internal.get_vault_secret(TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION internal.invoke_email_worker() TO service_role;
