-- ============================================================
-- CCIS DATABASE SECURITY HARDENING: FIX PROFILE SELF-UPDATE PRIVILEGE ESCALATION
--
-- NON-CANONICAL — DO NOT APPLY DIRECTLY.
-- This numbered script is kept for reference/documentation only.
-- The canonical tracked migration is:
--   supabase/migrations/20260818184500_fix_profile_self_update_privilege_escalation.sql
-- Apply via Supabase CLI: npx supabase db push --linked
-- ============================================================
