create table "internal"."email_worker_invocations" (
  "id"           bigint                   generated by default as identity not null,
  "requested_at" timestamp with time zone not null default now(),
  "request_id"   bigint,
  "status"       text                     not null,
  "error_code"   text,
  constraint "email_worker_invocations_pkey" primary key (id),
  constraint "email_worker_invocations_status_check" check ((status = ANY (ARRAY['requested'::text, 'configuration_error'::text, 'invocation_error'::text])))
);

grant delete, insert, maintain, references, select, trigger, truncate, update on table "internal"."email_worker_invocations" to "postgres";

grant insert, select on table "internal"."email_worker_invocations" to "service_role";
